apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: x8itv5ifw-python 
  janus-idp.io/tekton: x8itv5ifw-python
  backstage.io/kubernetes-id: x8itv5ifw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x8itv5ifw-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml